### ISSUE TITLE
It’s not clear what you’re trying to test

### ISSUE THREAD

**Issue by mauroservienti** [mehdihadeli/WebApplicationFactoryWithHost-Sample#1]
the test defined at 

https://github.com/mehdihadeli/test/blob/c8f7a271b9092c39e794884f64102cd0bcc5453d/SampleMiddlewareTests.cs#L6

tests nothing. What are you trying to test?

**Comment by mehdihadeli** [comment]
Hi @mauroservienti,
I just want to implement your [blog sample code](https://milestone.topics.it/2021/04/28/you-wanna-test-http.html), this is the same code as your blog post.
Should I create a separate web app with a `program.cs` or `startup.cs` for this, and then I should test the referenced app? Because in your post, you mentioned we don't need a startup class.

**Comment by mauroservienti** [comment]
Yes, you're right the snippets in the blog post are not enough. I raised #2 to add what's missing.
